export const sindhDistricts = [
  'Badin',
  'Dadu',
  'Ghotki',
  'Hyderabad',
  'Jacobabad',
  'Jamshoro',
  'Karachi Central',
  'Karachi East',
  'Karachi South',
  'Karachi West',
  'Kashmore',
  'Keamari',
  'Khairpur',
  'Korangi',
  'Larkana',
  'Malir',
  'Matiari',
  'Mirpur Khas',
  'Naushahro Firoze',
  'Qambar Shahdadkot',
  'Sanghar',
  'Shaheed Benazirabad',
  'Shikarpur',
  'Sujawal',
  'Sukkur',
  'Tando Allahyar',
  'Tando Muhammad Khan',
  'Tharparkar',
  'Thatta',
  'Umerkot',
]

export const talukasByDistrict: Record<string, string[]> = {
  Badin: [
    'Badin',
    'Matli',
    'Shaheed Fazil Rahu (Golarchi)',
    'Talhar',
    'Tando Bago',
  ],
  Sujawal: ['Jati', 'Kharo Chan', 'Mirpur Bathoro', 'Shah Bunder', 'Sujawal'],
  Thatta: ['Ghorabari', 'Keti Bunder', 'Mirpur Sakro', 'Thatta'],
  Dadu: ['Dadu', 'Johi', 'Khairpur Nathan Shah', 'Mehar'],
  Hyderabad: ['Hyderabad City', 'Hyderabad Rural', 'Latifabad', 'Qasimabad'],
  Jamshoro: ['Kotri', 'Manjhand', 'Sehwan Sharif', 'Thano Bula Khan'],
  Matiari: ['Hala', 'Matiari', 'Saeedabad'],
  'Tando Allahyar': ['Chamber', 'Jhando Mari', 'Tando Allahyar'],
  'Tando Muhammad Khan': [
    'Bulri Shah Karim',
    'Tando Ghulam Hyder',
    'Tando Muhammad Khan',
  ],
  'Karachi Central': [
    'Gulberg',
    'Liaquatabad',
    'Nazimabad',
    'New Karachi',
    'North Nazimabad',
  ],
  'Karachi East': [
    'Ferozabad',
    'Gulshan-e-Iqbal',
    'Gulzar-e-Hijri',
    'Jamshed Quarters',
  ],
  'Karachi South': ['Aram Bagh', 'Civil Line', 'Garden', 'Lyari', 'Saddar'],
  'Karachi West': ['Mango Pir', 'Mominabad', 'Orangi'],
  Keamari: ['Baldia', 'Harbour', 'Mauripur', 'SITE'],
  Korangi: ['Korangi', 'Landhi', 'Model Colony', 'Shah Faisal'],
  Malir: [
    'Airport',
    'Bin Qasim',
    'Gadap',
    'Ibrahim Hyderi',
    'Murad Memon',
    'Shah Murad',
  ],
  Jacobabad: ['Garhi Khairo', 'Jacobabad', 'Thul'],
  Kashmore: ['Kandhkot', 'Kashmore', 'Tangwani'],
  Larkana: ['Bakrani', 'Dokri', 'Larkana', 'Ratodero'],
  'Qambar Shahdadkot': [
    'Mirokhan',
    'Nasirabad',
    'Qambar',
    'Qubo Saeed Khan',
    'Shahdadkot',
    'Sijawal Junejo',
    'Warah',
  ],
  Shikarpur: ['Garhi Yasin', 'Khanpur', 'Lakhi Ghulam Shah', 'Shikarpur'],
  'Mirpur Khas': [
    'Digri',
    'Hussain Bux Mari',
    'Jhuddo',
    'Kot Ghulam Muhammad',
    'Mirpur Khas',
    'Shujabad',
    'Sindhri',
  ],
  Tharparkar: [
    'Chachro',
    'Dahli',
    'Diplo',
    'Islamkot',
    'Kaloi',
    'Mithi',
    'Nagarparkar',
  ],
  Umerkot: ['Kunri', 'Pithoro', 'Samaro', 'Umerkot'],
  'Naushahro Firoze': [
    'Bhiria',
    'Kandiaro',
    'Mehrabpur',
    'Moro',
    'Naushahro Firoze',
  ],
  Sanghar: [
    'Jam Nawaz Ali',
    'Khipro',
    'Sanghar',
    'Shahdadpur',
    'Sinjhoro',
    'Tando Adam',
  ],
  'Shaheed Benazirabad': ['Daur', 'Nawabshah', 'Qazi Ahmed', 'Sakrand'],
  Ghotki: ['Daharki', 'Ghotki', 'Khangarh', 'Mirpur Mathelo', 'Ubauro'],
  Khairpur: [
    'Faiz Ganj',
    'Gambat',
    'Khairpur',
    'Kingri',
    'Kot Diji',
    'Mirwah',
    'Nara',
    'Sobhodero',
  ],
  Sukkur: ['New Sukkur', 'Pano Aqil', 'Rohri', 'Salehpat', 'Sukkur City'],
}

export const genderOptions = ['Male', 'Female', 'Other', 'Prefer not to say']
export const bloodGroupOptions = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']

