/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DesignationHoldersRouteImport } from './routes/designation-holders'
import { Route as DesignationCardRouteImport } from './routes/designation-card'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CwcRouteImport } from './routes/cwc'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as CardRouteImport } from './routes/card'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyMemberNoRouteImport } from './routes/verify/$memberNo'
import { Route as ProgramsWelfareRouteImport } from './routes/programs/welfare'
import { Route as ProgramsHealthRouteImport } from './routes/programs/health'
import { Route as ProgramsEmploymentRouteImport } from './routes/programs/employment'
import { Route as ProgramsEducationRouteImport } from './routes/programs/education'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as CommitteesIdRouteImport } from './routes/committees/$id'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDesignationsRouteImport } from './routes/admin/designations'
import { Route as AdminCommitteesRouteImport } from './routes/admin/committees'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminAreaPermissionsRouteImport } from './routes/admin/area-permissions'
import { Route as VerifyOfficeBearerOfficeBearerIdRouteImport } from './routes/verify/office-bearer/$officeBearerId'
import { Route as ProgramsWelfareMyApplicationsRouteImport } from './routes/programs/welfare/my-applications'
import { Route as ProgramsWelfareApplyRouteImport } from './routes/programs/welfare/apply'
import { Route as ProgramsWelfareIdRouteImport } from './routes/programs/welfare/$id'
import { Route as ProgramsHealthMyApplicationsRouteImport } from './routes/programs/health/my-applications'
import { Route as ProgramsHealthApplyRouteImport } from './routes/programs/health/apply'
import { Route as ProgramsHealthIdRouteImport } from './routes/programs/health/$id'
import { Route as ProgramsEmploymentMyApplicationsRouteImport } from './routes/programs/employment/my-applications'
import { Route as ProgramsEmploymentApplyRouteImport } from './routes/programs/employment/apply'
import { Route as ProgramsEmploymentIdRouteImport } from './routes/programs/employment/$id'
import { Route as ProgramsEducationMyApplicationsRouteImport } from './routes/programs/education/my-applications'
import { Route as ProgramsEducationApplyRouteImport } from './routes/programs/education/apply'
import { Route as ProgramsEducationIdRouteImport } from './routes/programs/education/$id'
import { Route as AdminProgramsWelfareRouteImport } from './routes/admin/programs/welfare'
import { Route as AdminProgramsHealthRouteImport } from './routes/admin/programs/health'
import { Route as AdminProgramsEmploymentRouteImport } from './routes/admin/programs/employment'
import { Route as AdminProgramsEducationRouteImport } from './routes/admin/programs/education'
import { Route as AdminNewsIdRouteImport } from './routes/admin/news/$id'
import { Route as AdminMembersIdRouteImport } from './routes/admin/members/$id'
import { Route as AdminCommitteesIdRouteImport } from './routes/admin/committees/$id'
import { Route as AdminCmsSlugRouteImport } from './routes/admin/cms/$slug'
import { Route as AdminProgramsWelfareIdRouteImport } from './routes/admin/programs/welfare/$id'
import { Route as AdminProgramsHealthIdRouteImport } from './routes/admin/programs/health/$id'
import { Route as AdminProgramsEmploymentIdRouteImport } from './routes/admin/programs/employment/$id'
import { Route as AdminProgramsEducationIdRouteImport } from './routes/admin/programs/education/$id'
import { Route as AdminMembersIdDesignationCardRouteImport } from './routes/admin/members/$id/designation-card'
import { Route as AdminMembersIdCardRouteImport } from './routes/admin/members/$id/card'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignationHoldersRoute = DesignationHoldersRouteImport.update({
  id: '/designation-holders',
  path: '/designation-holders',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignationCardRoute = DesignationCardRouteImport.update({
  id: '/designation-card',
  path: '/designation-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CwcRoute = CwcRouteImport.update({
  id: '/cwc',
  path: '/cwc',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMemberNoRoute = VerifyMemberNoRouteImport.update({
  id: '/verify/$memberNo',
  path: '/verify/$memberNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWelfareRoute = ProgramsWelfareRouteImport.update({
  id: '/programs/welfare',
  path: '/programs/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsHealthRoute = ProgramsHealthRouteImport.update({
  id: '/programs/health',
  path: '/programs/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsEmploymentRoute = ProgramsEmploymentRouteImport.update({
  id: '/programs/employment',
  path: '/programs/employment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsEducationRoute = ProgramsEducationRouteImport.update({
  id: '/programs/education',
  path: '/programs/education',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const CommitteesIdRoute = CommitteesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommitteesRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignationsRoute = AdminDesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteesRoute = AdminCommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAreaPermissionsRoute = AdminAreaPermissionsRouteImport.update({
  id: '/area-permissions',
  path: '/area-permissions',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyOfficeBearerOfficeBearerIdRoute =
  VerifyOfficeBearerOfficeBearerIdRouteImport.update({
    id: '/verify/office-bearer/$officeBearerId',
    path: '/verify/office-bearer/$officeBearerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsWelfareMyApplicationsRoute =
  ProgramsWelfareMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsWelfareRoute,
  } as any)
const ProgramsWelfareApplyRoute = ProgramsWelfareApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsWelfareRoute,
} as any)
const ProgramsWelfareIdRoute = ProgramsWelfareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsWelfareRoute,
} as any)
const ProgramsHealthMyApplicationsRoute =
  ProgramsHealthMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsHealthRoute,
  } as any)
const ProgramsHealthApplyRoute = ProgramsHealthApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsHealthRoute,
} as any)
const ProgramsHealthIdRoute = ProgramsHealthIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsHealthRoute,
} as any)
const ProgramsEmploymentMyApplicationsRoute =
  ProgramsEmploymentMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsEmploymentRoute,
  } as any)
const ProgramsEmploymentApplyRoute = ProgramsEmploymentApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsEmploymentRoute,
} as any)
const ProgramsEmploymentIdRoute = ProgramsEmploymentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsEmploymentRoute,
} as any)
const ProgramsEducationMyApplicationsRoute =
  ProgramsEducationMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsEducationRoute,
  } as any)
const ProgramsEducationApplyRoute = ProgramsEducationApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsEducationRoute,
} as any)
const ProgramsEducationIdRoute = ProgramsEducationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsEducationRoute,
} as any)
const AdminProgramsWelfareRoute = AdminProgramsWelfareRouteImport.update({
  id: '/programs/welfare',
  path: '/programs/welfare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsHealthRoute = AdminProgramsHealthRouteImport.update({
  id: '/programs/health',
  path: '/programs/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsEmploymentRoute = AdminProgramsEmploymentRouteImport.update({
  id: '/programs/employment',
  path: '/programs/employment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsEducationRoute = AdminProgramsEducationRouteImport.update({
  id: '/programs/education',
  path: '/programs/education',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNewsRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteesIdRoute = AdminCommitteesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCommitteesRoute,
} as any)
const AdminCmsSlugRoute = AdminCmsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminProgramsWelfareIdRoute = AdminProgramsWelfareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProgramsWelfareRoute,
} as any)
const AdminProgramsHealthIdRoute = AdminProgramsHealthIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProgramsHealthRoute,
} as any)
const AdminProgramsEmploymentIdRoute =
  AdminProgramsEmploymentIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminProgramsEmploymentRoute,
  } as any)
const AdminProgramsEducationIdRoute =
  AdminProgramsEducationIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminProgramsEducationRoute,
  } as any)
const AdminMembersIdDesignationCardRoute =
  AdminMembersIdDesignationCardRouteImport.update({
    id: '/designation-card',
    path: '/designation-card',
    getParentRoute: () => AdminMembersIdRoute,
  } as any)
const AdminMembersIdCardRoute = AdminMembersIdCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AdminMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/committees': typeof CommitteesRouteWithChildren
  '/constitution': typeof ConstitutionRoute
  '/contact': typeof ContactRoute
  '/cwc': typeof CwcRoute
  '/dashboard': typeof DashboardRoute
  '/designation-card': typeof DesignationCardRoute
  '/designation-holders': typeof DesignationHoldersRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/area-permissions': typeof AdminAreaPermissionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/committees': typeof AdminCommitteesRouteWithChildren
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/cms/$slug': typeof AdminCmsSlugRoute
  '/admin/committees/$id': typeof AdminCommitteesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/verify/office-bearer/$officeBearerId': typeof VerifyOfficeBearerOfficeBearerIdRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/members/$id/designation-card': typeof AdminMembersIdDesignationCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/committees': typeof CommitteesRouteWithChildren
  '/constitution': typeof ConstitutionRoute
  '/contact': typeof ContactRoute
  '/cwc': typeof CwcRoute
  '/dashboard': typeof DashboardRoute
  '/designation-card': typeof DesignationCardRoute
  '/designation-holders': typeof DesignationHoldersRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/area-permissions': typeof AdminAreaPermissionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/committees': typeof AdminCommitteesRouteWithChildren
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/cms/$slug': typeof AdminCmsSlugRoute
  '/admin/committees/$id': typeof AdminCommitteesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/verify/office-bearer/$officeBearerId': typeof VerifyOfficeBearerOfficeBearerIdRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/members/$id/designation-card': typeof AdminMembersIdDesignationCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/committees': typeof CommitteesRouteWithChildren
  '/constitution': typeof ConstitutionRoute
  '/contact': typeof ContactRoute
  '/cwc': typeof CwcRoute
  '/dashboard': typeof DashboardRoute
  '/designation-card': typeof DesignationCardRoute
  '/designation-holders': typeof DesignationHoldersRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/area-permissions': typeof AdminAreaPermissionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/committees': typeof AdminCommitteesRouteWithChildren
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/cms/$slug': typeof AdminCmsSlugRoute
  '/admin/committees/$id': typeof AdminCommitteesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/verify/office-bearer/$officeBearerId': typeof VerifyOfficeBearerOfficeBearerIdRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/members/$id/designation-card': typeof AdminMembersIdDesignationCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/card'
    | '/committees'
    | '/constitution'
    | '/contact'
    | '/cwc'
    | '/dashboard'
    | '/designation-card'
    | '/designation-holders'
    | '/donate'
    | '/donors'
    | '/events'
    | '/gallery'
    | '/login'
    | '/manifesto'
    | '/news'
    | '/notifications'
    | '/register'
    | '/signup'
    | '/vision-mission'
    | '/admin/area-permissions'
    | '/admin/audit-logs'
    | '/admin/cms'
    | '/admin/committees'
    | '/admin/designations'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/roles'
    | '/committees/$id'
    | '/news/$slug'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/cms/$slug'
    | '/admin/committees/$id'
    | '/admin/members/$id'
    | '/admin/news/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/verify/office-bearer/$officeBearerId'
    | '/admin/members/$id/card'
    | '/admin/members/$id/designation-card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/card'
    | '/committees'
    | '/constitution'
    | '/contact'
    | '/cwc'
    | '/dashboard'
    | '/designation-card'
    | '/designation-holders'
    | '/donate'
    | '/donors'
    | '/events'
    | '/gallery'
    | '/login'
    | '/manifesto'
    | '/news'
    | '/notifications'
    | '/register'
    | '/signup'
    | '/vision-mission'
    | '/admin/area-permissions'
    | '/admin/audit-logs'
    | '/admin/cms'
    | '/admin/committees'
    | '/admin/designations'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/roles'
    | '/committees/$id'
    | '/news/$slug'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/cms/$slug'
    | '/admin/committees/$id'
    | '/admin/members/$id'
    | '/admin/news/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/verify/office-bearer/$officeBearerId'
    | '/admin/members/$id/card'
    | '/admin/members/$id/designation-card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/card'
    | '/committees'
    | '/constitution'
    | '/contact'
    | '/cwc'
    | '/dashboard'
    | '/designation-card'
    | '/designation-holders'
    | '/donate'
    | '/donors'
    | '/events'
    | '/gallery'
    | '/login'
    | '/manifesto'
    | '/news'
    | '/notifications'
    | '/register'
    | '/signup'
    | '/vision-mission'
    | '/admin/area-permissions'
    | '/admin/audit-logs'
    | '/admin/cms'
    | '/admin/committees'
    | '/admin/designations'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/roles'
    | '/committees/$id'
    | '/news/$slug'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/cms/$slug'
    | '/admin/committees/$id'
    | '/admin/members/$id'
    | '/admin/news/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/verify/office-bearer/$officeBearerId'
    | '/admin/members/$id/card'
    | '/admin/members/$id/designation-card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CardRoute: typeof CardRoute
  CommitteesRoute: typeof CommitteesRouteWithChildren
  ConstitutionRoute: typeof ConstitutionRoute
  ContactRoute: typeof ContactRoute
  CwcRoute: typeof CwcRoute
  DashboardRoute: typeof DashboardRoute
  DesignationCardRoute: typeof DesignationCardRoute
  DesignationHoldersRoute: typeof DesignationHoldersRoute
  DonateRoute: typeof DonateRoute
  DonorsRoute: typeof DonorsRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ManifestoRoute: typeof ManifestoRoute
  NewsRoute: typeof NewsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  VisionMissionRoute: typeof VisionMissionRoute
  ProgramsEducationRoute: typeof ProgramsEducationRouteWithChildren
  ProgramsEmploymentRoute: typeof ProgramsEmploymentRouteWithChildren
  ProgramsHealthRoute: typeof ProgramsHealthRouteWithChildren
  ProgramsWelfareRoute: typeof ProgramsWelfareRouteWithChildren
  VerifyMemberNoRoute: typeof VerifyMemberNoRoute
  VerifyOfficeBearerOfficeBearerIdRoute: typeof VerifyOfficeBearerOfficeBearerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designation-holders': {
      id: '/designation-holders'
      path: '/designation-holders'
      fullPath: '/designation-holders'
      preLoaderRoute: typeof DesignationHoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designation-card': {
      id: '/designation-card'
      path: '/designation-card'
      fullPath: '/designation-card'
      preLoaderRoute: typeof DesignationCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cwc': {
      id: '/cwc'
      path: '/cwc'
      fullPath: '/cwc'
      preLoaderRoute: typeof CwcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$memberNo': {
      id: '/verify/$memberNo'
      path: '/verify/$memberNo'
      fullPath: '/verify/$memberNo'
      preLoaderRoute: typeof VerifyMemberNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/welfare': {
      id: '/programs/welfare'
      path: '/programs/welfare'
      fullPath: '/programs/welfare'
      preLoaderRoute: typeof ProgramsWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/health': {
      id: '/programs/health'
      path: '/programs/health'
      fullPath: '/programs/health'
      preLoaderRoute: typeof ProgramsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/employment': {
      id: '/programs/employment'
      path: '/programs/employment'
      fullPath: '/programs/employment'
      preLoaderRoute: typeof ProgramsEmploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/education': {
      id: '/programs/education'
      path: '/programs/education'
      fullPath: '/programs/education'
      preLoaderRoute: typeof ProgramsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/committees/$id': {
      id: '/committees/$id'
      path: '/$id'
      fullPath: '/committees/$id'
      preLoaderRoute: typeof CommitteesIdRouteImport
      parentRoute: typeof CommitteesRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/designations': {
      id: '/admin/designations'
      path: '/designations'
      fullPath: '/admin/designations'
      preLoaderRoute: typeof AdminDesignationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committees': {
      id: '/admin/committees'
      path: '/committees'
      fullPath: '/admin/committees'
      preLoaderRoute: typeof AdminCommitteesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/area-permissions': {
      id: '/admin/area-permissions'
      path: '/area-permissions'
      fullPath: '/admin/area-permissions'
      preLoaderRoute: typeof AdminAreaPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/office-bearer/$officeBearerId': {
      id: '/verify/office-bearer/$officeBearerId'
      path: '/verify/office-bearer/$officeBearerId'
      fullPath: '/verify/office-bearer/$officeBearerId'
      preLoaderRoute: typeof VerifyOfficeBearerOfficeBearerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/welfare/my-applications': {
      id: '/programs/welfare/my-applications'
      path: '/my-applications'
      fullPath: '/programs/welfare/my-applications'
      preLoaderRoute: typeof ProgramsWelfareMyApplicationsRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/welfare/apply': {
      id: '/programs/welfare/apply'
      path: '/apply'
      fullPath: '/programs/welfare/apply'
      preLoaderRoute: typeof ProgramsWelfareApplyRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/welfare/$id': {
      id: '/programs/welfare/$id'
      path: '/$id'
      fullPath: '/programs/welfare/$id'
      preLoaderRoute: typeof ProgramsWelfareIdRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/health/my-applications': {
      id: '/programs/health/my-applications'
      path: '/my-applications'
      fullPath: '/programs/health/my-applications'
      preLoaderRoute: typeof ProgramsHealthMyApplicationsRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/health/apply': {
      id: '/programs/health/apply'
      path: '/apply'
      fullPath: '/programs/health/apply'
      preLoaderRoute: typeof ProgramsHealthApplyRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/health/$id': {
      id: '/programs/health/$id'
      path: '/$id'
      fullPath: '/programs/health/$id'
      preLoaderRoute: typeof ProgramsHealthIdRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/employment/my-applications': {
      id: '/programs/employment/my-applications'
      path: '/my-applications'
      fullPath: '/programs/employment/my-applications'
      preLoaderRoute: typeof ProgramsEmploymentMyApplicationsRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/employment/apply': {
      id: '/programs/employment/apply'
      path: '/apply'
      fullPath: '/programs/employment/apply'
      preLoaderRoute: typeof ProgramsEmploymentApplyRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/employment/$id': {
      id: '/programs/employment/$id'
      path: '/$id'
      fullPath: '/programs/employment/$id'
      preLoaderRoute: typeof ProgramsEmploymentIdRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/education/my-applications': {
      id: '/programs/education/my-applications'
      path: '/my-applications'
      fullPath: '/programs/education/my-applications'
      preLoaderRoute: typeof ProgramsEducationMyApplicationsRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/programs/education/apply': {
      id: '/programs/education/apply'
      path: '/apply'
      fullPath: '/programs/education/apply'
      preLoaderRoute: typeof ProgramsEducationApplyRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/programs/education/$id': {
      id: '/programs/education/$id'
      path: '/$id'
      fullPath: '/programs/education/$id'
      preLoaderRoute: typeof ProgramsEducationIdRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/admin/programs/welfare': {
      id: '/admin/programs/welfare'
      path: '/programs/welfare'
      fullPath: '/admin/programs/welfare'
      preLoaderRoute: typeof AdminProgramsWelfareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/health': {
      id: '/admin/programs/health'
      path: '/programs/health'
      fullPath: '/admin/programs/health'
      preLoaderRoute: typeof AdminProgramsHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/employment': {
      id: '/admin/programs/employment'
      path: '/programs/employment'
      fullPath: '/admin/programs/employment'
      preLoaderRoute: typeof AdminProgramsEmploymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/education': {
      id: '/admin/programs/education'
      path: '/programs/education'
      fullPath: '/admin/programs/education'
      preLoaderRoute: typeof AdminProgramsEducationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$id': {
      id: '/admin/news/$id'
      path: '/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof AdminNewsRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committees/$id': {
      id: '/admin/committees/$id'
      path: '/$id'
      fullPath: '/admin/committees/$id'
      preLoaderRoute: typeof AdminCommitteesIdRouteImport
      parentRoute: typeof AdminCommitteesRoute
    }
    '/admin/cms/$slug': {
      id: '/admin/cms/$slug'
      path: '/$slug'
      fullPath: '/admin/cms/$slug'
      preLoaderRoute: typeof AdminCmsSlugRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/programs/welfare/$id': {
      id: '/admin/programs/welfare/$id'
      path: '/$id'
      fullPath: '/admin/programs/welfare/$id'
      preLoaderRoute: typeof AdminProgramsWelfareIdRouteImport
      parentRoute: typeof AdminProgramsWelfareRoute
    }
    '/admin/programs/health/$id': {
      id: '/admin/programs/health/$id'
      path: '/$id'
      fullPath: '/admin/programs/health/$id'
      preLoaderRoute: typeof AdminProgramsHealthIdRouteImport
      parentRoute: typeof AdminProgramsHealthRoute
    }
    '/admin/programs/employment/$id': {
      id: '/admin/programs/employment/$id'
      path: '/$id'
      fullPath: '/admin/programs/employment/$id'
      preLoaderRoute: typeof AdminProgramsEmploymentIdRouteImport
      parentRoute: typeof AdminProgramsEmploymentRoute
    }
    '/admin/programs/education/$id': {
      id: '/admin/programs/education/$id'
      path: '/$id'
      fullPath: '/admin/programs/education/$id'
      preLoaderRoute: typeof AdminProgramsEducationIdRouteImport
      parentRoute: typeof AdminProgramsEducationRoute
    }
    '/admin/members/$id/designation-card': {
      id: '/admin/members/$id/designation-card'
      path: '/designation-card'
      fullPath: '/admin/members/$id/designation-card'
      preLoaderRoute: typeof AdminMembersIdDesignationCardRouteImport
      parentRoute: typeof AdminMembersIdRoute
    }
    '/admin/members/$id/card': {
      id: '/admin/members/$id/card'
      path: '/card'
      fullPath: '/admin/members/$id/card'
      preLoaderRoute: typeof AdminMembersIdCardRouteImport
      parentRoute: typeof AdminMembersIdRoute
    }
  }
}

interface AdminCmsRouteChildren {
  AdminCmsSlugRoute: typeof AdminCmsSlugRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsSlugRoute: AdminCmsSlugRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminCommitteesRouteChildren {
  AdminCommitteesIdRoute: typeof AdminCommitteesIdRoute
}

const AdminCommitteesRouteChildren: AdminCommitteesRouteChildren = {
  AdminCommitteesIdRoute: AdminCommitteesIdRoute,
}

const AdminCommitteesRouteWithChildren = AdminCommitteesRoute._addFileChildren(
  AdminCommitteesRouteChildren,
)

interface AdminNewsRouteChildren {
  AdminNewsIdRoute: typeof AdminNewsIdRoute
}

const AdminNewsRouteChildren: AdminNewsRouteChildren = {
  AdminNewsIdRoute: AdminNewsIdRoute,
}

const AdminNewsRouteWithChildren = AdminNewsRoute._addFileChildren(
  AdminNewsRouteChildren,
)

interface AdminMembersIdRouteChildren {
  AdminMembersIdCardRoute: typeof AdminMembersIdCardRoute
  AdminMembersIdDesignationCardRoute: typeof AdminMembersIdDesignationCardRoute
}

const AdminMembersIdRouteChildren: AdminMembersIdRouteChildren = {
  AdminMembersIdCardRoute: AdminMembersIdCardRoute,
  AdminMembersIdDesignationCardRoute: AdminMembersIdDesignationCardRoute,
}

const AdminMembersIdRouteWithChildren = AdminMembersIdRoute._addFileChildren(
  AdminMembersIdRouteChildren,
)

interface AdminProgramsEducationRouteChildren {
  AdminProgramsEducationIdRoute: typeof AdminProgramsEducationIdRoute
}

const AdminProgramsEducationRouteChildren: AdminProgramsEducationRouteChildren =
  {
    AdminProgramsEducationIdRoute: AdminProgramsEducationIdRoute,
  }

const AdminProgramsEducationRouteWithChildren =
  AdminProgramsEducationRoute._addFileChildren(
    AdminProgramsEducationRouteChildren,
  )

interface AdminProgramsEmploymentRouteChildren {
  AdminProgramsEmploymentIdRoute: typeof AdminProgramsEmploymentIdRoute
}

const AdminProgramsEmploymentRouteChildren: AdminProgramsEmploymentRouteChildren =
  {
    AdminProgramsEmploymentIdRoute: AdminProgramsEmploymentIdRoute,
  }

const AdminProgramsEmploymentRouteWithChildren =
  AdminProgramsEmploymentRoute._addFileChildren(
    AdminProgramsEmploymentRouteChildren,
  )

interface AdminProgramsHealthRouteChildren {
  AdminProgramsHealthIdRoute: typeof AdminProgramsHealthIdRoute
}

const AdminProgramsHealthRouteChildren: AdminProgramsHealthRouteChildren = {
  AdminProgramsHealthIdRoute: AdminProgramsHealthIdRoute,
}

const AdminProgramsHealthRouteWithChildren =
  AdminProgramsHealthRoute._addFileChildren(AdminProgramsHealthRouteChildren)

interface AdminProgramsWelfareRouteChildren {
  AdminProgramsWelfareIdRoute: typeof AdminProgramsWelfareIdRoute
}

const AdminProgramsWelfareRouteChildren: AdminProgramsWelfareRouteChildren = {
  AdminProgramsWelfareIdRoute: AdminProgramsWelfareIdRoute,
}

const AdminProgramsWelfareRouteWithChildren =
  AdminProgramsWelfareRoute._addFileChildren(AdminProgramsWelfareRouteChildren)

interface AdminRouteChildren {
  AdminAreaPermissionsRoute: typeof AdminAreaPermissionsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminCommitteesRoute: typeof AdminCommitteesRouteWithChildren
  AdminDesignationsRoute: typeof AdminDesignationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminNewsRoute: typeof AdminNewsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminMembersIdRoute: typeof AdminMembersIdRouteWithChildren
  AdminProgramsEducationRoute: typeof AdminProgramsEducationRouteWithChildren
  AdminProgramsEmploymentRoute: typeof AdminProgramsEmploymentRouteWithChildren
  AdminProgramsHealthRoute: typeof AdminProgramsHealthRouteWithChildren
  AdminProgramsWelfareRoute: typeof AdminProgramsWelfareRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAreaPermissionsRoute: AdminAreaPermissionsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminCommitteesRoute: AdminCommitteesRouteWithChildren,
  AdminDesignationsRoute: AdminDesignationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminNewsRoute: AdminNewsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminMembersIdRoute: AdminMembersIdRouteWithChildren,
  AdminProgramsEducationRoute: AdminProgramsEducationRouteWithChildren,
  AdminProgramsEmploymentRoute: AdminProgramsEmploymentRouteWithChildren,
  AdminProgramsHealthRoute: AdminProgramsHealthRouteWithChildren,
  AdminProgramsWelfareRoute: AdminProgramsWelfareRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommitteesRouteChildren {
  CommitteesIdRoute: typeof CommitteesIdRoute
}

const CommitteesRouteChildren: CommitteesRouteChildren = {
  CommitteesIdRoute: CommitteesIdRoute,
}

const CommitteesRouteWithChildren = CommitteesRoute._addFileChildren(
  CommitteesRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ProgramsEducationRouteChildren {
  ProgramsEducationIdRoute: typeof ProgramsEducationIdRoute
  ProgramsEducationApplyRoute: typeof ProgramsEducationApplyRoute
  ProgramsEducationMyApplicationsRoute: typeof ProgramsEducationMyApplicationsRoute
}

const ProgramsEducationRouteChildren: ProgramsEducationRouteChildren = {
  ProgramsEducationIdRoute: ProgramsEducationIdRoute,
  ProgramsEducationApplyRoute: ProgramsEducationApplyRoute,
  ProgramsEducationMyApplicationsRoute: ProgramsEducationMyApplicationsRoute,
}

const ProgramsEducationRouteWithChildren =
  ProgramsEducationRoute._addFileChildren(ProgramsEducationRouteChildren)

interface ProgramsEmploymentRouteChildren {
  ProgramsEmploymentIdRoute: typeof ProgramsEmploymentIdRoute
  ProgramsEmploymentApplyRoute: typeof ProgramsEmploymentApplyRoute
  ProgramsEmploymentMyApplicationsRoute: typeof ProgramsEmploymentMyApplicationsRoute
}

const ProgramsEmploymentRouteChildren: ProgramsEmploymentRouteChildren = {
  ProgramsEmploymentIdRoute: ProgramsEmploymentIdRoute,
  ProgramsEmploymentApplyRoute: ProgramsEmploymentApplyRoute,
  ProgramsEmploymentMyApplicationsRoute: ProgramsEmploymentMyApplicationsRoute,
}

const ProgramsEmploymentRouteWithChildren =
  ProgramsEmploymentRoute._addFileChildren(ProgramsEmploymentRouteChildren)

interface ProgramsHealthRouteChildren {
  ProgramsHealthIdRoute: typeof ProgramsHealthIdRoute
  ProgramsHealthApplyRoute: typeof ProgramsHealthApplyRoute
  ProgramsHealthMyApplicationsRoute: typeof ProgramsHealthMyApplicationsRoute
}

const ProgramsHealthRouteChildren: ProgramsHealthRouteChildren = {
  ProgramsHealthIdRoute: ProgramsHealthIdRoute,
  ProgramsHealthApplyRoute: ProgramsHealthApplyRoute,
  ProgramsHealthMyApplicationsRoute: ProgramsHealthMyApplicationsRoute,
}

const ProgramsHealthRouteWithChildren = ProgramsHealthRoute._addFileChildren(
  ProgramsHealthRouteChildren,
)

interface ProgramsWelfareRouteChildren {
  ProgramsWelfareIdRoute: typeof ProgramsWelfareIdRoute
  ProgramsWelfareApplyRoute: typeof ProgramsWelfareApplyRoute
  ProgramsWelfareMyApplicationsRoute: typeof ProgramsWelfareMyApplicationsRoute
}

const ProgramsWelfareRouteChildren: ProgramsWelfareRouteChildren = {
  ProgramsWelfareIdRoute: ProgramsWelfareIdRoute,
  ProgramsWelfareApplyRoute: ProgramsWelfareApplyRoute,
  ProgramsWelfareMyApplicationsRoute: ProgramsWelfareMyApplicationsRoute,
}

const ProgramsWelfareRouteWithChildren = ProgramsWelfareRoute._addFileChildren(
  ProgramsWelfareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CardRoute: CardRoute,
  CommitteesRoute: CommitteesRouteWithChildren,
  ConstitutionRoute: ConstitutionRoute,
  ContactRoute: ContactRoute,
  CwcRoute: CwcRoute,
  DashboardRoute: DashboardRoute,
  DesignationCardRoute: DesignationCardRoute,
  DesignationHoldersRoute: DesignationHoldersRoute,
  DonateRoute: DonateRoute,
  DonorsRoute: DonorsRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ManifestoRoute: ManifestoRoute,
  NewsRoute: NewsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  VisionMissionRoute: VisionMissionRoute,
  ProgramsEducationRoute: ProgramsEducationRouteWithChildren,
  ProgramsEmploymentRoute: ProgramsEmploymentRouteWithChildren,
  ProgramsHealthRoute: ProgramsHealthRouteWithChildren,
  ProgramsWelfareRoute: ProgramsWelfareRouteWithChildren,
  VerifyMemberNoRoute: VerifyMemberNoRoute,
  VerifyOfficeBearerOfficeBearerIdRoute: VerifyOfficeBearerOfficeBearerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
